# Generated by Django 4.1.5 on 2023-01-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre')),
                ('paterno', models.CharField(max_length=40, verbose_name='paterno')),
                ('materno', models.CharField(max_length=40, verbose_name='materno')),
                ('universidad', models.CharField(max_length=80, verbose_name='universidad')),
                ('celular', models.CharField(max_length=80, verbose_name='celular')),
                ('correo', models.EmailField(max_length=40, verbose_name='correo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
                'ordering': ['-created'],
            },
        ),
    ]
